services:
  - type: web
    name: details-mobile-back
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: detailsmobile-db
          property: connectionString
  - type: pspg
    name: detailsmobile-db
    plan: free
    databaseName: detailsmobile
    user: detailsmobile_user

